# Generated by Django 3.2.5 on 2021-07-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('is_executed', models.BooleanField(default=False)),
                ('day_added', models.DateTimeField(auto_now_add=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('time_todo', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
